docs: fix interface-tests readme usage
ipfs/js-stores pull request #247
Opened 2023-09-05 14:24 UTC by tabcat

Closes #246

2023-11-17 15:54 UTC, Marcel-G commented on packages/interface-datastore-tests/README.md
> +const { interfaceDatastoreTests as suite } from 'interface-datastore-tests')
```suggestion
import MyDatastore from './path/to/my-datastore'
import { interfaceDatastoreTests as suite } from 'interface-datastore-tests'
```

2023-11-17 15:54 UTC, Marcel-G commented on packages/interface-blockstore-tests/README.md
> +const { interfaceBlockstoreTests as suite } from 'interface-blockstore-tests')
```suggestion
import MyBlockstore from './path/to/my-blockstore'
import { interfaceBlockstoreTests as suite } from 'interface-blockstore-tests'
```

2023-12-14 21:21 UTC, SgtPooki requested changes

2023-12-14 21:21 UTC, SgtPooki commented on packages/interface-datastore-tests/README.md
>  const MyDatastore from './path/to/my-datastore')
```suggestion
```

2023-12-14 21:21 UTC, SgtPooki commented on packages/interface-blockstore-tests/README.md
>  const MyBlockstore from './path/to/my-blockstore')
```suggestion
```

2023-12-14 21:22 UTC, SgtPooki approved these changes

2023-12-14 23:02 UTC, merged