feat: replace fast-atomic-write with steno
ipfs/js-stores pull request #285
Opened 2023-12-14 23:02 UTC by SgtPooki

- feat(blockstore-fs): fast-write-atomic -> steno
- feat(datastore-fs): fast-write-atomic -> steno

fixes #284

2023-12-15 12:43 UTC, achingbrain requested changes

2023-12-15 12:43 UTC, achingbrain commented on packages/blockstore-fs/src/index.ts
> +      this.writers.delete(filePath)
I think this introduces a race condition.  If I try to write the same block from three different contexts, A, B and C

1. A does `this.writers.get`, it returns `null`, A does `this.writers.set`, starts `await writeFile`
2. B does `this.writers.get`, it returns `StenoWriter`, B starts `await writeFile`
3. A finishes `await writeFile`, A does `this.writers.delete`
4. C does `this.writers.get`, it returns `null`, C does `this.writers.set` starts `await writeFile`
5. B & C are now fighting: 💥 

You can fix this by using a reference count:

`this.writers` becomes `Map<string, { refs: number, writer: StenoWriter }>`

1. A does `this.writers.get`, it returns `null`, A does `this.writers.set` with refs 1, starts `await writeFile`
2. B does `this.writers.get`, it returns `StenoWriter`, B increments refs to 2, B starts `await writeFile`
3. A finishes `await writeFile`, A decrements refs, refs is 1
4. C does `this.writers.get`, it returns `StenoWriter`, C increments refs to 2, C starts `await writeFile`
5. B finishes `await writeFile`, A decrements refs, refs is 1
6. C finishes `await writeFile`, A decrements refs, refs is 0, C does `this.writers.delete`

There's also a memory leak - handling decrementing refs and removing things from `this.writers` needs to be done in a  `finally` block because if the call to `writeFile` throws, the `StenoWriter` will never be removed from `this.writers`.

The final thing is that if we have multiple processes waiting for for the writes of other processes to complete like this we may want to accept an `AbortOptions` and then use [race-signal](https://www.npmjs.com/package/race-signal) to allow callers to break out of any deadlocks that might occur.

2023-12-15 12:43 UTC, achingbrain commented on packages/blockstore-fs/src/index.ts
> +import { Writer as StenoWriter } from '@sgtpooki/steno-patched'
Can you please PR steno with the improvements?  It would be good to not depend on forks where possible.

2023-12-15 12:43 UTC, achingbrain commented on packages/blockstore-fs/src/index.ts
> +      // 2023-12-14: Is this still needed with steno?
This block handles the case where two processes (e.g. two [cluster](https://nodejs.org/api/cluster.html) workers) are using the same blockstore and try to write the same block simultaneously.

Steno [doesn't handle this](https://github.com/typicode/steno/issues/3), so I think yes.

Something like `flock` from [fs-ext](https://www.npmjs.com/package/fs-ext) might be better here (mentioned in the linked issue), since it uses the filesystem for locking instead of holding it in-process, though I've no idea about Windows support there.

2023-12-15 15:37 UTC, SgtPooki commented on packages/blockstore-fs/src/index.ts
> +import { Writer as StenoWriter } from '@sgtpooki/steno-patched'
Yep, its out there: https://github.com/typicode/steno/pull/32

2023-12-15 15:46 UTC, SgtPooki commented on packages/blockstore-fs/src/index.ts
> +import { Writer as StenoWriter } from '@sgtpooki/steno-patched'
By the way, after running the benchmarks mentioned in the description, I verified steno supports the different content types already so that we could use steno now with a `ts-expect-error`

2023-12-15 20:28 UTC, SgtPooki commented on packages/blockstore-fs/src/index.ts
> +      // 2023-12-14: Is this still needed with steno?
I'll add `flock` from `fs-ext` to https://github.com/SgtPooki/fast-write-atomic#benchmarks and see what happens

2023-12-15 20:30 UTC, SgtPooki commented on packages/blockstore-fs/src/index.ts
> +      // 2023-12-14: Is this still needed with steno?
we should also make sure we have a test for this.. i'll see about adding one

2023-12-15 20:31 UTC, SgtPooki commented on packages/blockstore-fs/src/index.ts
> +      this.writers.delete(filePath)
we should have a failing test for this.. i'll see about adding one

2023-12-17 08:23 UTC, SgtPooki commented on packages/blockstore-fs/src/index.ts
> +      // 2023-12-14: Is this still needed with steno?
FYI i've been doing some testing, and fast-write-atomic doesn't seem to be concurrency safe either, but i've got a modified steno that is now with fs-ext, though there are some issues with windows support there.

It's slower than steno, but still significantly faster than write-file-atomic and actually thread safe (as far as fs-ext.flock supports at least), but locking/unlocking is expected to increase some slowness. I added pRetry to retry the fs-ext locking, so that has some slight overhead too. Currently set retries to 1000, but real-world usecase could probably support retry of 100 (retry of 100 fails in my cluster test)

bench results for strings:

| Task Name                        | ops/sec | Average Time (ns)  | Margin | Samples |
|----------------------------------|---------|--------------------|--------|---------|
| string - write-file-atomic       | 98      | 10200464.169681072 | ±3.15% | 100     |
| string - fast-write-atomic       | 87      | 11492403.77008915  | ±2.62% | 100     |
| string - atomically              | 93      | 10701752.150654793 | ±3.81% | 100     |
| string - steno                   | 1,697   | 589000.475877025   | ±3.44% | 849     |
| string - @sgtpooki/steno-patched | 1,662   | 601492.9283768511  | ±4.86% | 832     |
| string - steno-custom.js         | 721     | 1385954.2634678679 | ±4.82% | 361     |

---

I'm going to see if I can wiggle my test into this library, but if you want to take a peek it's at https://github.com/SgtPooki/fast-write-atomic/blob/testing-concurrent/test-cluster-write.mjs

2023-12-17 08:27 UTC, SgtPooki commented on packages/blockstore-fs/src/index.ts
> +      // 2023-12-14: Is this still needed with steno?
Here's a test run of the cluster concurrency test:

```console
> node test-cluster-write.mjs 
Primary 59413 has started.
Worker 59418 has started.
Worker 59414 has started.
Worker 59419 has started.
Worker 59416 has started.
Worker 59420 has started.
Worker 59417 has started.
Worker 59415 has started.
Worker 59423 has started.
Worker 59421 has started.
Worker 59422 has started.
testing write of large string of length 107465

testing fwaWrite..........
file contents mismatch for fwaWrite
expected test-data-59417-1pzm...
got test-data-59423-1pzm...

testing stenoWrite.worker 59420 threw an error when trying to write file with stenoWrite
worker 59417 threw an error when trying to write file with stenoWrite
worker 59421 threw an error when trying to write file with stenoWrite
worker 59422 threw an error when trying to write file with stenoWrite
worker 59419 threw an error when trying to write file with stenoWrite
worker 59423 threw an error when trying to write file with stenoWrite
worker 59416 threw an error when trying to write file with stenoWrite
worker 59418 threw an error when trying to write file with stenoWrite
worker 59414 threw an error when trying to write file with stenoWrite

file contents mismatch for stenoWrite
expected test-data-59414-1pzm...
got test-data-59418-1pzm...

testing customStenoWrite....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
testing manualWrite..........
file contents mismatch for manualWrite
expected test-data-59415-1pzm...
got test-data-59417-1pzm...

testing manualWriteFd....................
file contents mismatch for manualWriteFd
expected test-data-59423-1pzm...
got test-data-59421-1pzm...

Primary 59413 is exiting.
The following write functions failed concurrent write test:
         * fwaWrite
         * stenoWrite
         * manualWrite
         * manualWriteFd 
```

2023-12-17 21:56 UTC, SgtPooki commented on packages/blockstore-fs/src/index.ts
> +      // 2023-12-14: Is this still needed with steno?
I just tested this on windows, and the custom-steno.mjs passes there as well as manualWrite and manualWrite with file-descriptors:


```
The following write functions failed concurrent write test:
         * fwaWrite
         * stenoWrite
```

2024-02-10 18:00 UTC, achingbrain commented on packages/blockstore-fs/src/index.ts
> +import { Writer as StenoWriter } from '@sgtpooki/steno-patched'
It looks like your patch got merged, this can probably revert to regular `steno` now?

2024-04-19 14:47 UTC, SgtPooki commented on packages/blockstore-fs/src/index.ts
> +import { Writer as StenoWriter } from '@sgtpooki/steno-patched'
this is done as of [`57048de` (#285)](https://github.com/ipfs/js-stores/pull/285/commits/57048debcdd2efb771e77d806231dd9c22538aeb)

2024-04-19 18:05 UTC, SgtPooki commented on packages/blockstore-fs/src/index.ts
> +      // 2023-12-14: Is this still needed with steno?
[a test for concurrent writing](https://github.com/search?q=repo%3Aipfs%2Fjs-stores%20can%20survive%20concurrent%20writes&type=code) already exists but i'm not sure it's testing full multi-cluster/process concurrency because all of the writes are handled by the same event loop.

I've got another test on main thread i'm going to add and then rebase this PR on top of it.

2024-04-19 18:16 UTC, SgtPooki commented on packages/blockstore-fs/src/index.ts
> +      // 2023-12-14: Is this still needed with steno?
created in https://github.com/ipfs/js-stores/pull/305

2024-04-19 18:24 UTC, SgtPooki commented on packages/blockstore-fs/src/index.ts
> +      this.writers.delete(filePath)
Idk about testing for a race condition here other than the other concurrency tests we already have, but I did a ton of testing on [the other large comment thread](https://github.com/ipfs/js-stores/pull/285#discussion_r1427926375) and it seems like caching writers doesn't even give us a benefit, so I'll remove all this complexity entirely and see that it still passes tests (including https://github.com/ipfs/js-stores/pull/305)

2024-04-23 15:59 UTC, wemeetagain approved these changes

2024-07-25 15:28 UTC, SgtPooki commented
@achingbrain anything else needed for this one or can I merge it?

2024-07-26 17:11 UTC, achingbrain commented on packages/blockstore-fs/src/index.ts
>        // fast-write-atomic writes a file to a temp location before renaming it.
Given that we no longer use fwa is this error detection still necessary?

2024-07-26 17:11 UTC, achingbrain commented on packages/datastore-fs/src/index.ts
>        // fast-write-atomic writes a file to a temp location before renaming it.
Same comment as https://github.com/ipfs/js-stores/pull/285/files#r1693365294

2024-07-26 17:13 UTC, achingbrain requested changes
LGTM, just the question over the error detection we used to do for fast-write-atomic.

2024-08-06 14:40 UTC, SgtPooki commented on packages/blockstore-fs/src/index.ts
>        // fast-write-atomic writes a file to a temp location before renaming it.
@achingbrain steno also writes to a temp file before renaming it to the new one. I looked into this a while back but haven't in a while. let me double check if https://github.com/ipfs/js-stores/pull/305 still passes when removing this error handling

2024-08-06 15:18 UTC, SgtPooki commented on packages/blockstore-fs/src/index.ts
>        // fast-write-atomic writes a file to a temp location before renaming it.
fails with 

```
  2 passing (1s)
  1 failing

  1) FsBlockstore
       can survive concurrent writes:
     Error: ENOENT: no such file or directory, rename '/var/folders/bl/_gl5_59s11v7qz5ysd6bfgb00000gn/T/test-0.1889829891040602/LY/.BCIQPGZJ6QLZOFG3OP45NLMSJUWGJCO72QQKHLDTB6FXIB6BDSLRQYLY.data.tmp' -> '/var/folders/bl/_gl5_59s11v7qz5ysd6bfgb00000gn/T/test-0.1889829891040602/LY/BCIQPGZJ6QLZOFG3OP45NLMSJUWGJCO72QQKHLDTB6FXIB6BDSLRQYLY.data'
      at rename (node:internal/fs/promises:782:10)
      at file:///Users/sgtpooki/code/work/ipshipyard/ipfs/js-stores/node_modules/steno/lib/index.js:55:17
      at retryAsyncOperation (file:///Users/sgtpooki/code/work/ipshipyard/ipfs/js-stores/node_modules/steno/lib/index.js:14:20)
      at Writer.#write (file:///Users/sgtpooki/code/work/ipshipyard/ipfs/js-stores/node_modules/steno/lib/index.js:54:13)
      at writeFile (file:///Users/sgtpooki/code/work/ipshipyard/ipfs/js-stores/packages/blockstore-fs/src/index.ts:35:5)
      at FsBlockstore.put (file:///Users/sgtpooki/code/work/ipshipyard/ipfs/js-stores/packages/blockstore-fs/src/index.ts:151:7)
      at file:///Users/sgtpooki/code/work/ipshipyard/ipfs/js-stores/packages/blockstore-fs/test/index.spec.ts:155:48
      at async Promise.all (index 3)
      at Context.<anonymous> (file:///Users/sgtpooki/code/work/ipshipyard/ipfs/js-stores/packages/blockstore-fs/test/index.spec.ts:154:5)
```

2024-08-06 15:18 UTC, SgtPooki commented on packages/blockstore-fs/src/index.ts
>        // fast-write-atomic writes a file to a temp location before renaming it.
So yes, we still need this. I will update the comment

2024-08-06 15:31 UTC, SgtPooki commented on packages/datastore-fs/src/index.ts
>        // fast-write-atomic writes a file to a temp location before renaming it.
yea it's needed. I updated the comment itself

2024-08-09 12:02 UTC, achingbrain approved these changes

2024-08-09 12:02 UTC, merged